import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    screens: {
      'xs': '480px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1400px',
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        elevated: "hsl(var(--background-elevated))",
        surface: "hsl(var(--background-surface))",
        hover: "hsl(var(--background-hover))",
        sage: {
          DEFAULT: "hsl(var(--primary))",
          light: "hsl(var(--sage-light))",
          dark: "hsl(var(--sage-dark))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        tertiary: {
          foreground: "hsl(var(--tertiary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius-lg)",
        md: "var(--radius)",
        sm: "var(--radius-sm)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "slide-up": { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "nav-breathe": { "0%, 100%": { transform: "scale(1)" }, "50%": { transform: "scale(1.03)" } },
        "avatar-breathe": { "0%, 100%": { transform: "translate(-50%, -50%) translateZ(0) translateY(0) rotate(0deg)", borderRadius: "75% 25% 65% 35% / 60% 40% 60% 40%" }, "33%": { transform: "translate(-50%, -50%) translateZ(0) translateY(-10px) rotate(-2deg)", borderRadius: "72% 28% 62% 38% / 58% 42% 58% 42%" }, "66%": { transform: "translate(-50%, -50%) translateZ(0) translateY(-6px) rotate(1deg)", borderRadius: "74% 26% 66% 34% / 62% 38% 62% 38%" } },
        "avatar-blink": { "0%, 44%, 56%, 100%": { transform: "scaleY(1) translateZ(0)" }, "50%": { transform: "scaleY(0.1) translateZ(0)" } },
        "avatar-float": { "0%, 100%": { transform: "translateY(0) rotate(0deg) scale(1)" }, "33%": { transform: "translateY(-8px) rotate(-2deg) scale(1.02)" }, "66%": { transform: "translateY(-4px) rotate(1deg) scale(1.01)" } },
        "pulse-glow": { "0%, 100%": { opacity: "0.4", transform: "translate(-50%, -50%) scale(1)" }, "50%": { opacity: "0.7", transform: "translate(-50%, -50%) scale(1.15)" } },
        "message-in": { from: { opacity: "0", transform: "translateY(12px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "message-avatar-breathe": { "0%, 100%": { transform: "scale(1)" }, "50%": { transform: "scale(1.05)" } },
        "thinking-sway": { "0%, 100%": { transform: "rotate(0deg)" }, "25%": { transform: "rotate(5deg)" }, "75%": { transform: "rotate(-4deg)" } },
        "thinking-eyes": { "0%, 100%": { transform: "scaleY(0.6)" }, "50%": { transform: "scaleY(1)" } },
        "thinking-bounce": { "0%, 60%, 100%": { transform: "translateY(0)", opacity: "0.4" }, "30%": { transform: "translateY(-6px)", opacity: "1" } },
        "listening-pulse": { "0%, 100%": { transform: "translate(-50%, -50%) translateZ(0) scale(1)" }, "50%": { transform: "translate(-50%, -50%) translateZ(0) scale(1.05)" } },
        "seed-breathe": { "0%, 100%": { transform: "translate(-50%, -50%) translateZ(0) scale(1) translateY(0) rotate(0deg)" }, "33%": { transform: "translate(-50%, -50%) translateZ(0) scale(1.02) translateY(-8px) rotate(-2deg)" }, "66%": { transform: "translate(-50%, -50%) translateZ(0) scale(1.01) translateY(-4px) rotate(1deg)" } },
        "glow-pulse": { "0%, 100%": { opacity: "0.4", transform: "translate(-50%, -50%) scale(1)" }, "50%": { opacity: "0.6", transform: "translate(-50%, -50%) scale(1.1)" } },
        "drift-1": { "0%, 100%": { transform: "translate(0, 0)" }, "50%": { transform: "translate(80px, 50px)" } },
        "drift-2": { "0%, 100%": { transform: "translate(0, 0)" }, "50%": { transform: "translate(-50px, -60px)" } },
        "step-enter": { from: { opacity: "0", transform: "translateY(20px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "step-exit": { from: { opacity: "1", transform: "translateY(0)" }, to: { opacity: "0", transform: "translateY(-20px)" } },
        "element-enter": { from: { opacity: "0", transform: "translateY(20px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "confused-sway": { "0%, 100%": { transform: "translate(-50%, -50%) rotate(0deg)" }, "25%": { transform: "translate(-50%, -50%) rotate(8deg)" }, "50%": { transform: "translate(-50%, -50%) rotate(0deg)" }, "75%": { transform: "translate(-50%, -50%) rotate(-8deg)" } },
        "confused-blink": { "0%, 30%, 50%, 100%": { transform: "scaleY(1)" }, "40%": { transform: "scaleY(0.1)" } },
        "float-up": { "0%": { opacity: "0", transform: "translateY(0)" }, "30%": { opacity: "0.6" }, "100%": { opacity: "0", transform: "translateY(-30px)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-up": "slide-up 0.4s ease-out",
        "nav-breathe": "nav-breathe 5s ease-in-out infinite",
        "avatar-breathe": "avatar-breathe 5s ease-in-out infinite",
        "avatar-blink": "avatar-blink 5s ease-in-out infinite",
        "avatar-float": "avatar-float 5s ease-in-out infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        "message-in": "message-in 0.4s ease-out",
        "message-avatar-breathe": "message-avatar-breathe 5s ease-in-out infinite",
        "thinking-sway": "thinking-sway 2s ease-in-out infinite",
        "thinking-eyes": "thinking-eyes 2s ease-in-out infinite",
        "thinking-bounce": "thinking-bounce 1.2s ease-in-out infinite",
        "listening-pulse": "listening-pulse 2.5s ease-in-out infinite",
        "seed-breathe": "seed-breathe 5s ease-in-out infinite",
        "glow-pulse": "glow-pulse 3s ease-in-out infinite",
        "drift-1": "drift-1 30s ease-in-out infinite",
        "drift-2": "drift-2 35s ease-in-out infinite",
        "step-enter": "step-enter 0.6s ease forwards",
        "step-exit": "step-exit 0.3s ease forwards",
        "element-enter": "element-enter 0.8s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "confused-sway": "confused-sway 4s ease-in-out infinite",
        "confused-blink": "confused-blink 3s ease-in-out infinite",
        "float-up": "float-up 2s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
